language: node_js
node_js:
  - "stable"

before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

script: 
  - npm install
  - npm run build

deploy: 
  provider: surge
  skip_cleanup: true
  domain: nawfal4756-animated-website.surge.sh
  project: ./build/

on:
  branch: master